replicaCount: 1
image:
  repository: https://github.com/Waves-Ducks-Team/item
  tag: stable
  pullPolicy: Always
application:
  track: stable
  tier: web
service:
  name: web
  type: ClusterIP
  port: 3004
resources:
