{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "observer.fullname" . }}
  labels:
    app: {{ template "observer.appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: {{ template "observer.appname" . }}
    tier: "{{ .Values.application.tier }}"
{{- end -}}
