version: "3"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: api
    volumes:
      - ./services/api:/item/services/app
      - /item/services/app/node_modules
    command: yarn dev
    environment:
      CHAIN_ID: T
      REDIS_URL: redis://redis:6379
      PRISMA_ENDPOINT: http://prisma:4466
      BUCKET_NAME: ${BUCKET_NAME}
      S3_TOKEN: ${S3_TOKEN}
      S3_SECRET: ${S3_SECRET}
    ports:
      - "4000:4000"
    links:
      - redis
      - prisma
  redis:
    image: redis
    ports:
      - "6379:6379"
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
