version: "3"
services:
  dev:
    build: ./
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
    environment:
      NETWORK: testnet
      REDIS_URL: redis://redis:6379
      PRISMA_HOST: prisma
      BUCKET_NAME: ${BUCKET_NAME}
      S3_TOKEN: ${S3_TOKEN}
      S3_SECRET: ${S3_SECRET}
    ports:
      - "4000:4000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      - "3004:3004"
    links:
      - redis
      - prisma
  redis:
    image: redis
    ports:
      - "6379:6379"
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
