replicaCount: 1
image:
  repository: https://github.com/Waves-Ducks-Team/item
  tag: stable
  pullPolicy: Always
application:
  track: stable
  tier: web
service:
  name: web
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
  url: http://my.host.com/
ingress:
  email: nobody@nobody.io
  privateKeySecretRef: example-issuer-account-key
  enabled: true
resources:

