version: 2.1

aliases:
  - &restore-yarn-cache
    name: Restore Yarn package cache
    keys:
      - v1-dependencies-{{ checksum "yarn.lock" }}
      - v1-dependencies-

  - &save-yarn-cache
    name: Save Yarn package cache
    key: v1-dependencies-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
      - ~/.cache/yarn

  - &bootstrap
    name: Lerna bootstrap
    command: yarn bootstrap

  - &build-packages
    name: Build all packages
    command: yarn build

defaults: &defaults
  working_directory: ~/item

node_defaults: &node_defaults
  <<: *defaults
  docker:
    - image: circleci/node:11

jobs:
  checkout_env:
    <<: *node_defaults
    steps:
      - checkout
      - restore_cache: *restore-yarn-cache
      - run: yarn --frozen-lockfile
      - run: *bootstrap
      - save_cache: *save-yarn-cache
      - persist_to_workspace:
          root: .
          paths: .

  build:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/item
      - run: *build-packages
      - persist_to_workspace:
          root: .
          paths:
            - packages/*/dist

  test_unit:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/item
      - run:
          name: Run Unit Tests
          command: yarn test

workflows:
  test:
    jobs:
      - checkout_env
      - build:
          requires:
            - checkout_env
      - test_unit:
          requires:
            - build
