version: 2.1

aliases:
  - &restore-yarn-cache
    name: Restore Yarn package cache
    keys:
      - v1-dependencies-{{ checksum "yarn.lock" }}
      - v1-dependencies-

  - &save-yarn-cache
    name: Save Yarn package cache
    key: v1-dependencies-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
      - ~/.cache/yarn

  - &bootstrap
    name: Lerna bootstrap
    command: yarn bootstrap

  - &build
    name: Build all services & packages
    command: yarn build

  - &start
    name: Start all services in the background
    command: yarn start
    background: true

defaults: &defaults
  working_directory: ~/item

node_defaults: &node_defaults
  <<: *defaults
  docker:
    - image: circleci/node:11

prisma_config: &prisma_config
  PRISMA_CONFIG: |
    port: 4466
    databases:
      default:
        connector: postgres
        host: postgres
        port: 5432
        user: prisma
        password: prisma
        migrations: true

jobs:
  checkout_env:
    <<: *node_defaults
    steps:
      - checkout
      - restore_cache: *restore-yarn-cache
      - run: yarn --frozen-lockfile
      - run: *bootstrap
      - save_cache: *save-yarn-cache
      - persist_to_workspace:
          root: .
          paths: .
  build:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/item
      - run: *build

  test_unit:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/item
      - run:
          name: Run Unit Tests
          command: yarn test

workflows:
  test:
    jobs:
      - checkout_env
      - build:
          requires:
            - checkout_env
      - test_unit:
          requires:
            - build
