{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "api.fullname" . }}
  labels:
    app: {{ template "api.appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version| replace "+" "_" }}"
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - {{ template "api.hostname" .Values.service.url }}
    secretName: {{ template "api.fullname" . }}-tls
  rules:
  - host: {{ template "api.hostname" .Values.service.url }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "api.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
{{- end -}}
