apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  JWT_SECRET: {{ .Values.jwtSecret | b64enc | quote }}
  S3_SECRET: {{ .Values.s3Secret | b64enc | quote }}
  ALGOLIA_API_SECRET: {{ .Values.algoliaApiSecret | b64enc | quote }}