apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  jwt-secret: {{ .Values.jwt.secret | b64enc | quote }}
  s3-secret: {{ .Values.s3.secret | b64enc | quote }}
  algolia-api-secret: {{ .Values.algolia.apiSecret | b64enc | quote }}