apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  jwt-secret: {{ .Values.global.jwtSecret | b64enc | quote }}
  s3-secret: {{ .Values.global.s3Secret | b64enc | quote }}
  algolia-api-secret: {{ .Values.global.algoliaApiSecret | b64enc | quote }}