apiVersion: v1
description: Item core chart
name: item
version: 0.0.1
dependencies:
- name: prisma
  version: 1.2.1
  repository: "https://kubernetes-charts.storage.googleapis.com/"
  condition: prisma.enabled
- name: redis
  version: 9.5.0
  repository: "https://kubernetes-charts.storage.googleapis.com/"
  condition: redis.enabled
- name: api
  version: 0.0.1
  repository: "file://./services/api"
  condition: api.enabled
  tags:
  - api
- name: observer
  version: 0.0.1
  repository: "file://./services/observer"
  condition: observer.enabled
  tags:
  - observer