apiVersion: v1
description: Item core chart
name: item
version: 0.0.1
dependencies:
- name: prisma
  version: 1.2.1
  repository: "https://kubernetes-charts.storage.googleapis.com/"
  condition: prisma.enabled
- name: api
  version: 0.0.1
  condition: api.enabled
  tags:
  - api