application:
  track: stable
  tier: web
api:
  enabled: false
  name: web
  type: ClusterIP
  externalPort: 3000
  internalPort: 3000
  url: http://my.host.com/
prisma:
  enabled: true
  image:
    tag: 1.34-heroku
resources:
