apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "api.appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: {{ template "api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "api.appname" . }}
  template:
    metadata:
      labels:
        app: {{ template "api.appname" . }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        command: ["yarn"]
        args: ["start"]
        env:
        - name: NODE_ENV
          value: {{ .Values.releaseOverride | quote }}
        - name: PORT
          value: {{ .Values.service.internalPort | quote }}
        - name: DEBUG
          value: api
        - name: PRISMA_ENDPOINT
          value: {{ .Values.global.prismaEndpoint | quote }}
        - name: S3_TOKEN
          value: {{ .Values.global.s3Token | quote }}
        - name: S3_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: s3-secret
        - name: ALGOLIA_APP_ID
          value: {{ .Values.global.algoliaAppId | quote }}
        - name: ALGOLIA_API_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: algolia-api-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: jwt-secret
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: "{{ .Values.service.name }}"
          containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 15
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 5
          timeoutSeconds: 3
        resources:
{{ toYaml .Values.resources | indent 12 }}
      restartPolicy: Always
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}
