name: Build and Deploy to GKE

on:
  push:
    branches:
    - master
#    paths:
#    - 'services/api/*'

# Environment variables available to all jobs and steps in this workflow
env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GKE_ZONE: us-central1-a
  GKE_CLUSTER: item-cluster-1
  REPLICAS: 1
  SERVICE_NAME: api
  IMAGE: api
  KUBE_NAMESPACE: item

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker

    # Build the Docker image
    - name: Build
      run: |
        docker build -t gcr.io/$GCP_PROJECT/$IMAGE:$GITHUB_SHA \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" ./services/$SERVICE_NAME

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker push gcr.io/$GCP_PROJECT/$IMAGE:$GITHUB_SHA

    # Install helm
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
        chmod 700 get_helm.sh
        ./get_helm.sh

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GCP_PROJECT
        kubectl describe namespace "$KUBE_NAMESPACE" || kubectl create namespace "$KUBE_NAMESPACE"
        helm dependency update charts/$SERVICE_NAME/
        helm upgrade --install \
          --wait \
          --set service.enabled="true" \
          --set image.repository="gcr.io/$GCP_PROJECT/$IMAGE" \
          --set image.tag="$GITHUB_SHA" \
          --set image.pullPolicy=IfNotPresent \
          --set replicaCount="$REPLICAS" \
          --set prisma.enabled="true" \
          --set prisma.nameOverride="prisma" \
          --namespace="$KUBE_NAMESPACE" \
          "$SERVICE_NAME" \
          charts/$SERVICE_NAME/
