name: Item - Prepare dependencies

on:
  push:
    branches:
    - 'releases/**'
#    paths:
#    - 'item/**'
#    - '!item/services/**'

# Environment variables available to all jobs and steps in this workflow
env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GKE_ZONE: us-central1-a
  GKE_CLUSTER: item-cluster-1
  REPLICAS: 1
  RELEASE_NAME: production
  NAMESPACE: item

jobs:
  setup-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker

    # Install helm
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
        chmod 700 get_helm.sh
        ./get_helm.sh

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      env:
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        S3_TOKEN: ${{ secrets.S3_TOKEN }}
        S3_SECRET: ${{ secrets.S3_SECRET }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        ALGOLIA_API_SECRET: ${{ secrets.ALGOLIA_API_SECRET }}
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GCP_PROJECT
        kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE
        helm dependency update item/
        helm upgrade --install \
          --wait \
          --set releaseOverride="$RELEASE_NAME" \
          --set prismaEndpoint="http://$RELEASE_NAME-prisma.$NAMESPACE:4466" \
          --set redisUrl="redis://$RELEASE_NAME-redis-master.$NAMESPACE:6379" \
          --set s3Token="$S3_TOKEN" \
          --set algoliaAppId="$ALGOLIA_APP_ID" \
          --set jwtSecret="$JWT_SECRET" \
          --set s3Secret="$S3_SECRET" \
          --set algoliaApiSecret="$ALGOLIA_API_SECRET" \
          --set prisma.enabled="true" \
          --set prisma.nameOverride="prisma" \
          --set prisma.database.host="$POSTGRES_HOST" \
          --set prisma.database.user="$POSTGRES_USER" \
          --set prisma.database.password="$POSTGRES_PASSWORD" \
          --set prisma.database.port="5432" \
          --set redis.enabled="true" \
          --set redis.nameOverride="redis" \
          --namespace="$NAMESPACE" \
          "$RELEASE_NAME" \
          item/
