name: Item - Deploy dependencies to cluster

on:
  push:
    branches:
    - master
#    paths:
#    - 'services/api/*'

# Environment variables available to all jobs and steps in this workflow
env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GKE_ZONE: us-central1-a
  GKE_CLUSTER: item-cluster-1
  KUBE_NAMESPACE: item

jobs:
  setup-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker

    # Install helm
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
        chmod 700 get_helm.sh
        ./get_helm.sh

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      env:
        RELEASE_NAME: production
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GCP_PROJECT
        kubectl describe namespace "$KUBE_NAMESPACE" || kubectl create namespace "$KUBE_NAMESPACE"
        helm dependency update item/
        helm upgrade --install \
          --wait \
          --timeout 120s \
          --set global.prismaEndpoint="http://$RELEASE_NAME-prisma:4466" \
          --set global.jwtSecret="$JWT_SECRET" \
          --set global.s3Token="$S3_TOKEN" \
          --set global.s3Secret="$S3_SECRET" \
          --set global.algoliaAppId="$ALGOLIA_APP_ID" \
          --set global.algoliaApiSecret="$ALGOLIA_API_SECRET" \
          --set prisma.enabled="true" \
          --set prisma.nameOverride="prisma" \
          --set prisma.database.host="$POSTGRES_HOST" \
          --set prisma.database.user="$POSTGRES_USER" \
          --set prisma.database.password="$POSTGRES_PASSWORD" \
          --set prisma.database.port="5432" \
          --set api.enabled="false" \
          --namespace="$KUBE_NAMESPACE" \
          "$RELEASE_NAME" \
          item/
