name: Observer - Build & deploy to cluster

on:
  push:
    branches:
    - 'master'
    paths:
    - 'services/observer/**'
    - 'item/services/observer/**'

# Environment variables available to all jobs and steps in this workflow
env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  REPLICAS: 1
  SERVICE_NAME: observer
  IMAGE: observer
  RELEASE_NAME: production
  NAMESPACE: item-observer

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.4.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker

    # Build the Docker image
    - name: Build
      run: |
        docker build -t gcr.io/$GCP_PROJECT/$IMAGE:$GITHUB_SHA \
          --build-arg SERVICE_NAME="$SERVICE_NAME" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker push gcr.io/$GCP_PROJECT/$IMAGE:$GITHUB_SHA

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      env:
        S3_TOKEN: ${{ secrets.S3_TOKEN }}
        S3_SECRET: ${{ secrets.S3_SECRET }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        ALGOLIA_API_SECRET: ${{ secrets.ALGOLIA_API_SECRET }}
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GCP_PROJECT
        kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE
        helm repo add stable https://charts.helm.sh/stable
        helm upgrade --install \
          --wait \
          --set releaseOverride="$RELEASE_NAME" \
          --set image.repository="gcr.io/$GCP_PROJECT/$IMAGE" \
          --set image.tag="$GITHUB_SHA" \
          --set image.pullPolicy=IfNotPresent \
          --set replicaCount="$REPLICAS" \
          --set prismaEndpoint="http://$RELEASE_NAME-prisma.item.svc.cluster.local:4466" \
          --set redisUrl="redis://$RELEASE_NAME-redis-master.item.svc.cluster.local:6379" \
          --set s3Token="$S3_TOKEN" \
          --set algoliaAppId="$ALGOLIA_APP_ID" \
          --set jwtSecret="$JWT_SECRET" \
          --set s3Secret="$S3_SECRET" \
          --set algoliaApiSecret="$ALGOLIA_API_SECRET" \
          --namespace="$NAMESPACE" \
          "$RELEASE_NAME" \
          item/services/$SERVICE_NAME/
